version: '3.8'

services:
  app:
    image: confeiteiro:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://app.automacaototal.com
      - NEXT_PUBLIC_SUPABASE_URL=https://jtzhuvqkszsveybakbwp.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0emh1dnFrc3pzdmV5YmFrYndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczODM5MjMsImV4cCI6MjA4Mjk1OTkyM30.aGrQn6Z26HISMTdpOWzYFNj3qAYGH92Kxt6HXegAeJM
      - NEXT_PUBLIC_API_URL=https://apiwp.automacaototal.com
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.confeiteiro.rule=Host(`app.automacaototal.com`)"
        - "traefik.http.routers.confeiteiro.entrypoints=websecure"
        - "traefik.http.routers.confeiteiro.tls.certresolver=letsencrypt"
        - "traefik.http.services.confeiteiro.loadbalancer.server.port=3000"
    networks:
      - network_public

networks:
  network_public:
    external: true
